config/routes.rb
Keriakoo::Application.routes.draw do
  get "reference_commodity/new"

  root :to => "home#index"

  devise_for :users
  resources :users, :only => :show
  resources :reference_units
  resources :reference_commodities

end

app/models/reference_commodity.rb
class ReferenceCommodity < ActiveRecord::Base
end

app/models/reference_unit.rb
class ReferenceUnit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/reference_commodities_controller.rb
class ReferenceCommoditiesController < ApplicationController
  def new
    @reference_commodity = ReferenceCommodity.new
  end
  
  def index
    @reference_commodities = ReferenceCommodity.find(:all)
  end
  
  def create
  @reference_commodity = ReferenceCommodity.new(params[:reference_commodity])

  respond_to do |format|
    if @reference_commodity.save
      format.html { redirect_to(@reference_commodity, :notice => 'Reference commodity was successfully created.') }
      format.xml  { render :xml => @reference_commodity, :status => :created, :location => @reference_commodity }
      format.json  { render json: @reference_commodity, status: :created, location: @reference_commodity }
   else
      format.html { render :action => "new" }
      format.xml  { render :xml => @reference_commodity.errors, :status => :unprocessable_entity }
      format.json { render json: @reference_commodity.errors, status: :unprocessable_entity }
    end
  end
  end

  def show
	 @reference_commodities = ReferenceCommodity.find(params[:id])
  end


end

app/controllers/reference_units_controller.rb
class ReferenceUnitsController < ApplicationController

  def new
    @reference_unit = ReferenceUnit.new
  end

  def create
  @reference_unit = ReferenceUnit.new(params[:reference_unit])

  respond_to do |format|
    if @reference_unit.save
      format.html { redirect_to(@reference_unit, :notice => 'Reference unit was successfully created.') }
      format.xml  { render :xml => @reference_unit, :status => :created, :location => @reference_unit }
      format.json  { render json: @reference_unit, status: :created, location: @reference_unit }
   else
      format.html { render :action => "new" }
      format.xml  { render :xml => @reference_unit.errors, :status => :unprocessable_entity }
      format.json { render json: @reference_unit.errors, status: :unprocessable_entity }
    end
  end
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reference_commodity_helper.rb
module ReferenceCommodityHelper
end

app/helpers/reference_units_helper.rb
module ReferenceUnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

app/views/layouts/_commodity_form.html.erb
<%= form_for (@reference_commodity)  do |f| %>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :commodity %><br />
    <%= f.text_field :commodity %>
  </div>
  <div class="field">
    <%= f.label :language, "What language?" %><br />
    <%= f.text_field :language %>
  </div>
 <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

app/views/layouts/_units_form.html.erb
<%= form_for (@reference_unit)  do |f| %>
  <div class="field">
    <%= f.label :commodity %><br />
    <%= f.text_field :commodity %>
  </div>
  <div class="field">
    <%= f.label :language, "What language?" %><br />
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :wholesale_unit %><br />
    <%= f.text_field :wholesale_unit %>
  </div>
    <div class="field">
    <%= f.label :retail_unit %><br />
    <%= f.text_field :retail_unit %>
  </div>
 <div class="field">
    <%= f.label :receipt_unit %><br />
    <%= f.text_field :receipt_unit %>
 <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Keriakoo</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= params[:controller] %>">
    <div id="container" class="container">
      <header>
        <nav>
          <ul class="hmenu">
            <%= render 'shared/navigation' %>
          </ul>
        </nav>
        <%- flash.each do |name, msg| -%>
          <%= content_tag :div, msg, :id => "flash_\#{name}" if msg.is_a?(String) %>
        <%- end -%>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>
      <footer>
      </footer>
    </div> <!--! end of #container -->
  </body>
</html>

app/views/reference_commodities/index.html.erb
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reference_commodities.each do |ref| %>
  <tr>
    <td><%= link_to 'Show', reference_commodities %></td>
    <td><%= ref.id %></td>
    <td><%= ref.type %></td>
    <td><%= ref.commodity %></td>
    <td><%= ref.language %></td>
    <td><%= link_to 'Edit', edit_reference_commodities_path(ref) %></td>
    <td><%= link_to 'Destroy', opening, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/reference_commodities/new.html.erb
<%= render 'layouts/commodity_form' %>

app/views/reference_commodities/show.html.erb
Reference commodity shows up here.

app/views/reference_units/new.html.erb
<%= render 'layouts/units_form' %>

app/views/reference_units/show.html.erb
show.html.erb

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Sign up', new_user_registration_path)  %>
  </li>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>